### ISSUE TITLE
[Feature Request]: A definitive list of Linux packages and dependencies

### ISSUE THREAD

**Issue by stephepush** [openvinotoolkit/stable-diffusion-webui#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I'm just asking that there be a single page/source where I can get the list of required packages for Linux required to get stable diffusion with the OpenVino acceleration configuration working at optimal speed on Intel Arc

### Proposed workflow

I am currently trying to run Stable Diffusion with an Intel Arc A770, and I'm only getting ~9.8it/s as opposed to the 14+it/s shown in the Tom's Hardware article that was recently posted. I am trying to see if there are any packages that I'm missing or that need to be updated to reach those speeds. I've looked at instructions for baremetal Linux installs, as well as instructions setting up SD and Intel Arc within Docker Containers, and still can't get the speeds shown in the Tom's Hardware article. There are many pages on the Intel site showing different ways to setup Stable diffusion, but I think it would be best if there was a definitive list of packages needed, that can be compared by a user, to run SD w/ OpenVino on an Intel Arc card.

### Additional information

I'm using Ubuntu 22.04, installed Python 3.10.12 (I'll double check this when I have the chance to get back to the system I'm running this all on), upgraded Mesa to the bleeding edge version, upgraded the system to kernel 6.4.12 and installed OpenAPI manually all in an effort to boost the iterations per second, only to get an increase of about .5 it/s.

**Comment by devangaggarwal** [comment]
Toms Hardware is showing images generated per minute as compared to it/s. The performance you are getting on A770 is the expected performance.
