### ISSUE TITLE
[Bug]: stable-diffusion-webui\webui-user.bat was unexpected

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [openvinotoolkit/stable-diffusion-webui#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm trying to reinstall Stable Diffusion with OpenVINO, but now I'm getting this weird error "Diffusion\stable-diffusion-webui\webui-user.bat was unexpected."

This was the command I entered : "C:\Stable Diffusion\stable-diffusion-webui>first-time-runner.bat"

For now I only cloned the GitHub repo and went in the stable-diffusion-webui folder, trying to run first-time-runner.bat

### Steps to reproduce the problem

Said everything above

### What should have happened?

Not give this error

### Version or Commit where the problem happens

Idk? Latest?

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Other GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
C:\Stable Diffusion\stable-diffusion-webui>first-time-runner.bat
Diffusion\stable-diffusion-webui\webui-user.bat était inattendu.
```

**Comment by qiacheng** [comment]
could you try removing the space in  the folder "Stable Diffusion"? it looks like the error is caused by the space in path. Thanks for addressing this and we will update the setup script

**Comment by TheWonderfulTartiflette** [comment]
@qiacheng thanks, this worked :)
