### ISSUE TITLE
[Feature Request]: use previously cached IR models

### ISSUE THREAD

**Issue by abdulhakam** [openvinotoolkit/stable-diffusion-webui#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I am currently testing this repo with a single model and found that after restarting the app(shutting down and restarting again from CLI, did not try from webui), the script creates the model again even if I load previous settings(including the prompt itself), so the suggestion I have is to store multiple preconfigured IR models.

### Proposed workflow

- adding a new tab in the webUI that will create configurations.
- in that tab, we set resolution, batch size, scheduler, device(cpu/gpu) etc.
- there will be a button that will create the required IR file according to the configuration.
- in the text2img tab, when we select accelerate with OpenVINO, it will have an option to use premade IR model.
- selecting the premade IR model will automatically sets batch size, resolution, etc. (or maybe also disables them)
- if someone even restarts the computer, it will have the option to load a premade IR model.

### Additional information

adding a new tab to create configurations is not important you can just add a checkbox "save this IR model" that will enable a textfield to name the configuration or something similar.

**Comment by devangaggarwal** [comment]
This issue is fixed now with this PR: https://github.com/openvinotoolkit/stable-diffusion-webui/pull/34
