### ISSUE TITLE
[Bug]: torch-install.bat  invalid

### ISSUE THREAD

**Issue by alexgang** [openvinotoolkit/stable-diffusion-webui#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

the specific Torch and Torchvision is no longer exist 

### Steps to reproduce the problem

run torch-install.bat 

### What should have happened?

orch 2.1.0 dev installation completed.

### Version or Commit where the problem happens

the specific Torch and Torchvision is no longer exist 

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Other GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
the specific Torch and Torchvision is no longer exist
```

### List of extensions

the specific Torch and Torchvision is no longer exist 

### Console logs

```Shell
the specific Torch and Torchvision is no longer exist
```

**Comment by qiacheng** [comment]
thanks for reporting, fix is now committed to use 20230716 torch dev package. we are working on implementing some ops that supports newer torch dev package as well

https://github.com/openvinotoolkit/stable-diffusion-webui/commit/c0da929e39267aaed1833f5471141f6c5af25c59
